In [1]:
list1=[17,2,8,23]
list2=[6,5,20,13]

In [2]:
list1+list2

[17, 2, 8, 23, 6, 5, 20, 13]

In [3]:
t1=(3,6,9,5)*3

In [4]:
t1

(3, 6, 9, 5, 3, 6, 9, 5, 3, 6, 9, 5)

In [5]:
import numpy as xy

In [6]:
list1_array=xy.array(list1)
list2_array=xy.array(list2)

In [7]:
list1_array+list2_array

array([23,  7, 28, 36])

In [8]:
t1_arr=xy.array(t1)
print(t1_arr)
print(type(t1_arr))

[3 6 9 5 3 6 9 5 3 6 9 5]
<class 'numpy.ndarray'>


In [9]:
(t1_arr)*3

array([ 9, 18, 27, 15,  9, 18, 27, 15,  9, 18, 27, 15])

In [10]:
arr0d=xy.array(90)
print(arr0d)
print(arr0d.ndim)
print(type(arr0d))

90
0
<class 'numpy.ndarray'>


In [11]:
arr1d=xy.array([25,89,43,16,33])
print(arr1d)
print(arr1d.ndim)
print(type(arr1d))

[25 89 43 16 33]
1
<class 'numpy.ndarray'>


In [12]:
arr2d=xy.array([[25,89,43,16,33],[5,6,8,2,10]])

In [13]:
### lists do not allow mathematical operations,but arrays aloow elementwise mathematical computations.
#### Lists support multiple data types,while arrays support only homogeneous data type.

In [14]:
arr1d=xy.array([25,89,43,16,33],dtype='float')
print(arr1d)
print(arr1d.ndim)
print(arr1d.dtype)


[25. 89. 43. 16. 33.]
1
float64


In [15]:
len(list1)

4

In [16]:
list1_array.size

4

In [18]:
import numpy as np
arr2d=np.array([[6,3,4,5],[1,2,3,4]])
arr2d

array([[6, 3, 4, 5],
       [1, 2, 3, 4]])

#### Attributes and methods of the array class

In [23]:
arr0d= np.array(50)
print(arr0d)
print(arr0d.ndim) # ndim gives us the number of dimensions in the array
print(arr0d.dtype) # returns the datatype of the elements in the array
print(arr0d.size) # returns the number of elements stored in the array

50
0
int32
1


In [25]:
arr1d=np.array([10,15,25,30])
print(arr1d)
print(arr1d.ndim) # ndim gives us the number of dimensions in the array
print(arr1d.dtype) # returns the datatype of the elements in the array
print(arr1d.size) # returns the number of elements stored in the array


[10 15 25 30]
1
int32
4


In [27]:
arr2d=np.array([[10,15,25,30],[2,5,6,8],[5,15,13,18]])
print(arr2d)
print(arr2d.ndim) # ndim gives us the number of dimensions in the array
print(arr2d.dtype) # returns the datatype of the elements in the array
print(arr2d.size) # returns the number of elements stored in the array
print(arr2d.shape) # returns the number of rows and columns in the array



[[10 15 25 30]
 [ 2  5  6  8]
 [ 5 15 13 18]]
2
int32
12
(3, 4)


* Every 1D data which we combine to create higher dimensional arrays should have the same size.
* If we find the product of the elements returned by the shape attribute,we get the size of the array

In [36]:
arr3d=np.array([[[1,8],[2,3]],[[4,5],[6,7]],[[8,9],[10,11]]])
print(arr3d)
print(arr3d.ndim) # ndim gives us the number of dimensions in the array
print(arr3d.dtype) # returns the datatype of the elements in the array
print(arr3d.size) # returns the number of elements stored in the array
print(arr3d.shape) # returns the number of 2D arrays we combine,number of rows in each 2D array, and columns in each 2D array


[[[ 1  8]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
3
int32
12
(3, 2, 2)


### add and remove dimensions of an array:

In [39]:
arr10=np.arange(1,13)
arr10

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [41]:
#convert this 1D array to 2D:
arr11=arr10.reshape(3,4)
print(arr11)
print(arr11.ndim)
print(arr11.shape)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)


In [43]:
##convert the 1D array to 3D array:
arr12=arr10.reshape(2,3,2)
print(arr12)
print(arr12.ndim)
print(arr12.shape)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


#### To convert higher dimensional arrays to the lowest dimension(1D) we use two inbuilt methods of the array class. flatten() and ravel()

In [46]:
res1d=arr12.flatten()
res1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [48]:
res2=arr11.ravel()
res2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
### Q) Create a 1d array with 8 integer values. Name it 'a',then convert 'a' to a 2D array and name it 'b'
### In the third step convert 'b' to a 3D array 'c'.

import numpy as np
a=np.arange(8)
print(a,'\n')
b=a.reshape(2,4)
print(b,'\n')
c=b.reshape(2,2,2)
print(c)

[0 1 2 3 4 5 6 7] 

[[0 1 2 3]
 [4 5 6 7]] 

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [4]:
#### Q) reduce the dimensions of 'c' to get back the original 1D data.
d=c.flatten()
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
arr16=np.arange(1,17,1).reshape(4,4)
arr16

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [10]:
arr16[2,1]

np.int64(10)

In [13]:
#slice out the elements of the third column
arr16[0:4,2]

array([ 3,  7, 11, 15])

In [16]:
#slice out the 1st and 3rd rows
arr16[0:4:2,0:4]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [32]:
#reverse the rows of arr16
print(arr16[::-1,:])


[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [33]:
#reverse the columns of arr16
arr16[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

In [34]:
#slice values 10,11,12 from arr16
arr16[2,1:]

array([10, 11, 12])

In [31]:
#slice elements 8 and 12
arr16[1:3,3]

array([ 8, 12])